version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '/'
    reviewers:
      - 'hanthor'
    labels:
      - 'dependencies'
      - 'security'
    allow:
      - dependency-type: 'all'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '/'
    labels:
      - 'dependencies'
      - 'ci'
    allow:
      - dependency-type: 'all'
